import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/usercontext";
import { DriverProvider } from "./context/captaincontext"; // Import the context
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <div className="layout-container">
        <UserProvider><DriverProvider> {/* ✅ Now all child routes can access useDriver() */}
              {children}
            </DriverProvider></UserProvider>
          
          
        </div>
      </body>
    </html>
  );
}
